# Generated by Django 5.2.7 on 2025-10-23 21:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_hora_agendada', models.DateTimeField(verbose_name='data e hora agendada')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('E', 'Em andamento'), ('C', 'Concluído'), ('X', 'Cancelado')], default='P', max_length=1, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_hora_agendada'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor estimado')),
                ('duracao_prevista', models.DurationField(blank=True, help_text='Formato: HH:MM:SS', null=True, verbose_name='duração prevista')),
                ('realizado', models.BooleanField(default=False, verbose_name='realizado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='site_principal.agendamento')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=12, verbose_name='placa')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='modelo')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='site_principal.cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='site_principal.veiculo'),
        ),
    ]
