# Generated by Django 5.2.7 on 2025-11-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='km_atual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=12, unique=True, verbose_name='placa'),
        ),
    ]
