# Generated by Django 5.2.7 on 2025-11-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0002_veiculo_km_atual_veiculo_marca_alter_veiculo_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='chassi'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='renavam'),
        ),
    ]
