# Generated by Django 5.2.7 on 2025-11-05 23:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0003_veiculo_chassi_veiculo_cor_veiculo_observacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=32, verbose_name='status')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='data de abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='data de encerramento')),
                ('km_atendimento', models.PositiveIntegerField(blank=True, null=True, verbose_name='km atendimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor total')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='site_principal.veiculo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
