# Generated by Django 5.2.7 on 2025-11-06 03:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0004_ordemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('fabricante', models.CharField(blank=True, max_length=100, verbose_name='fabricante')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='preço unitário')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='estoque atual')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['-criado_em'],
            },
        ),
    ]
