# Generated by Django 5.2.7 on 2025-11-06 03:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0005_peca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoExecutado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor')),
                ('duracao_estimada_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='duração estimada (h)')),
                ('data_execucao', models.DateTimeField(blank=True, null=True, verbose_name='data de execução')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_executados', to='site_principal.ordemservico')),
            ],
            options={
                'verbose_name': 'Serviço Executado',
                'verbose_name_plural': 'Serviços Executados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
