# Generated by Django 5.2.7 on 2025-11-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0006_servicoexecutado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoexecutado',
            name='funcionario_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID do funcionário'),
        ),
    ]
