# Generated by Django 5.2.7 on 2025-11-06 04:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0007_servicoexecutado_funcionario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaUtilizada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1, verbose_name='quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_utilizadas', to='site_principal.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='site_principal.peca')),
            ],
            options={
                'verbose_name': 'Peça Utilizada',
                'verbose_name_plural': 'Peças Utilizadas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
